ndlib/QA_tests

- README.md
@jeremyf / @danhorst 
I updated the readme, but I'm seeing this message: "This branch is 1 commit ahead, 5 commits behind master"
Probably should have run a git pull on local before starting to make changes on the branch?
> adding deploy and test instructions

- spec/curate/pages/faq_page.rb
Filled in some basic tests for identifying that FAQ page is functioning.
> Add QA tests for FAQ page

- README.md
Adding rubucop instruction to readme
> Adding rubucop instruction.

- spec/curate/functional/func_curate_spec.rb
- spec/curate/pages/catalog_page.rb
- spec/curate/pages/faq_page.rb
- spec/curate/pages/home_page.rb
Set up separate pages for home and catalog-search, with some initial tests in each.
> Dltp 699 lkr tests

- spec/curate/pages/about_page.rb
> adding spec for about page

- Gemfile
- Gemfile.lock
- spec/curate/functional/func_curate_spec.rb
- spec/spec_helper.rb
> Adding  TwP/logging

- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/curate/functional/func_curate_spec.rb
- spec/curate/pages/catalog_page.rb
- spec/curate/pages/departments_page.rb
Add tests going from the "Materials by department" page to the search results page.
> Lkr qa tests

- spec/curate/functional/func_curate_spec.rb
- spec/curate/pages/catalog_page.rb
- spec/curate/pages/departments_page.rb
Refactor hash parameter into DepartmentalLink class parameter
> Refactoring to value object

- spec/curate/functional/func_curate_spec.rb
- spec/spec_support/verify_network.rb
Committing these to avoid merge conflict grief.
> Adding timestamp

- spec/spec_support/example_logging.rb
https://github.com/ndlib/QA_tests/issues/49
log_filename needed to go back one more directory level in File.expand_path
> Fix for Issue# 49

- spec/spec_support/test_runtime.rb
https://en.wikipedia.org/wiki/ISO_8601
> Setting runID in ISO_8601 format.

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- spec/spec_support/cloudwatch_event_handler.rb
- spec/spec_support/json_output_formatter.rb
PR to send custom JSON output results from Rspec as cloudwatch events.
> Hp cloudwatch events

- spec/spec_support/swagger_handler.rb
- spec/viceroy/integration/int_viceroy_spec.rb
- spec/viceroy/viceroy_config.yml
- spec/viceroy/viceroy_repo_config.yml
- spec/viceroy/viceroy_spec_helper.rb
* Adding support for private git repositories
* Parameterizing swagger definition URL based on repository URL from a config file
> Modifications to Swagger handler

- spec/curate/pages/loggedin_page.rb
- spec/curate/pages/login_page.rb
I missed changing account_details_updated_flag to
account_details_updated. This was causing the if condition to
always evaluate to false and skipping the validation.
> Missed validation of 'My Delegates' button

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/account_page.rb
- spec/webRenovation/pages/base_page.rb
- spec/webRenovation/pages/courses_page.rb
- spec/webRenovation/utilities/login.rb
- spec/webRenovation/webRenovation_config.yml
- spec/webRenovation/webRenovation_spec_helper.rb
The login tests will work once [this](https://github.com/ndlib/monarch/pull/72) Monarch PR is merged and deployed. 
I had to load base_page.rb in the spec helper first because all other pages will inherit from it and the random require order was causing issues.
> Webreno personal page

- spec/spec_support/test_runtime.rb
* Addressing issue with tmp/screenshots directory not being found.
* Adding documentation
* Directory cleanup mechanism used to delete latest dir instead of oldest one
> Screenshots error

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- spec/viceroy/integration/int_viceroy_spec.rb
- spec/viceroy/viceroy_config.yml
This test only checks for a 200 response code and the scenario when a user is not logged in.
> Viceroy API test

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/account_page.rb
- spec/webRenovation/pages/base_page.rb
- spec/webRenovation/pages/home_page.rb
- spec/webRenovation/pages/pathfinder_page.rb
- Add the pathfinder page type for testing, and test one of them. 
- Account page needed updating for tests to work
- Remove extraneous username from base page
> Pathfinder Page Type

- .gitignore
- spec/curate/pages/show_article.rb
Fixes bug in curate functional test scenario "Show an Article" in regards to to show_article.rb
https://jira.library.nd.edu/browse/DLTP-1008
> Mh curate dtlp 1008

- README.md
- spec/spec_support/example_logging.rb
* Uncommenting verify_network_traffic to enable as default behavior
* Adding toggles documentation to README
> Hp enable verify network traffic

- spec/sipity/functional/etd_spec.rb
- spec/sipity/pages/cas_login_page.rb
- spec/sipity/pages/dashboard.rb
- spec/sipity/pages/etd_submission_page.rb
- spec/sipity/pages/etd_welcome.rb
- spec/sipity/pages/home_page.rb
- spec/sipity/pages/new_deposit.rb
- spec/sipity/pages/signed_in_page.rb
- spec/sipity/pages/submitted_etd.rb
Tested on pre-prod. I tried to keep one of the test users from having
done the first time login so that it can be tested later.  Viewing
submitted etd's results in an error because it does not keep the user
logged in.
> All Sipity functional test scenarios

- spec/hesburghsite/functional/func_hesburghsite_spec.rb
- spec/hesburghsite/hesburghsite_config.yml
- spec/hesburghsite/hesburghsite_spec_helper.rb
Creates new spec folder, hesburghsite, and creates the config.yml and spec_helper files under that folder.  Also, adds functional folder with the func_hesburghsite_spec.rb file in it.  Adds test cases 1-9 into the func_hesburghsite_spec.rb file.
Use cases for test cases 1-9 from:
https://docs.google.com/spreadsheets/d/10yo_X20lXymyOeKu33rJBzfrbe_FdBIweVw22duCnXA/edit#gid=248186373
> Mh hesburgh

- spec/hours/hours_config.yml
- spec/hours/hours_repo_config.yml
- spec/hours/hours_spec_helper.rb
- spec/hours/integration/int_hours_spec.rb
- spec/spec_support/response_validator.rb
* Creating a ResponseValidator class to validate integration test results
* Creates folder structure, configs and spec for 'hours' endpoint
> Integration test validator with 'hours' API

- spec/osf/functional/func_osf_spec.rb
- spec/osf/osf_config.yml
- spec/osf/osf_spec_helper.rb
- spec/osf/pages/login_page.rb
- spec/spec_support/inject_sleep.rb
Creates the necessary files and folders for osf tests.  Also updates inject_slep.rb to include the fill_in method as some login fields need time after filling in before clicking submit.  
Note: osf_spec_helper has code forcing the use of tlsv1.2 driver since the OSF website rejects ssl requests.
> Mh osf func

- config/deploy.rb
- config/deploy/production.rb
Adding Jenkins support for different specs to run on remote server.
> Adding Jenkins support

- spec/curate/pages/login_page.rb
- spec/osf/pages/login_page.rb
- spec/sipity/pages/cas_login_page.rb
The bodies of the login pages in test folders were altered to remove the
main body of the code but leave the methods customized for each test.
This allows the main body to be kept in a class in spec support that all
tests can use.
> Updates login pages for all tests to use global login page

- Gemfile
- Gemfile.lock
The gem source code can be found at:
https://github.com/contentful/contentful.rb
> Adding contentful gem

- bin/write_contentful_slugs_to_csv.rb
As urls are need for the google drive file, this script now generates urls as well as the slug
> adds url generation with slugs

- spec/spec_support/request_builder.rb
- spec/viceroy/integration/int_viceroy_spec.rb
Uses the request builder to simplify the integration test.  Updates the
request builder to properly test for non security APIs.
> Updates viceroy int test to use request builder

- spec/microfilms/functional/func_microfilms_spec.rb
Test 4 tests if you can click the letter associated with the "k" directory
> Updates microfilms to test 4.

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/base_page.rb
- spec/webRenovation/pages/home_page.rb
Creates new scenarios for site.  Some may need to be changed due to ongoing changes to the site. Changes will most likely need to be made for the webRenovation/pages as they hold much of basic outline testing.
> Hp webren changes

- Rakefile
As written the tests were incorrectly handling floors. I normalized
that behavior (e.g. floors are found in /floors/:slug) instead of /:slug
> Updating web renovation accessibility tests

- spec/spec_support/request_builder.rb
- spec/spec_support/swagger_handler.rb
* Checks for a path parameter and applies it to the path
* Adds additional logging 
* Fixes Rubocop warnings
> Hp gatekeeper test

- spec/spec_support/path_parameterizer.rb
- spec/spec_support/request_builder.rb
Replacing the singular aleph_system_ids lookup with a more generalized
solution.
> Adding more verbose handling of parameters

- bin/run_tests
- spec/spec_support/example_logging_constants.rb
- spec/spec_support/test_runtime.rb
We do not want to hit Contentful for rendering images.
> Adding network check for Contentful

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/base_page.rb
As the login button has changed back to being the login button which
then turns into the my account button so a variable has been added to
the base page to keep track of logged in status.  The logged in scenarios
have been updated to pass a value to the loggedin variable.
> Updates base_page.rb and the logged in scenarios due to design changes

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/hours_page.rb
The hours page file checks to make sure all of the hours for all of the
libraries are on the page.  The hours_page file also checks to make sure
the url is correct for the page.  The scenario tests the functionality
of going to the hours page from the homepage.
> Creates an hours_page.rb file and scenario 'Go to Hours page'

- config/deploy.rb
- config/deploy/production.rb
- spec/spec_support/path_parameterizer.rb
- spec/spec_support/request_builder.rb
- spec/spec_support/swagger_handler.rb
* Adds a method in PathParameterizer module to add query parameters to the request URL
* Exposes 'parameters' value from the swagger decorator
* Jenkins support for recommendationEngine test
> Hp query parameterizer

- spec/webRenovation/functional/func_webRenovation_spec.rb
* Removing js_error suppression
* Added missing expect statements
> Hp webren refactor

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/courses_page.rb
- spec/webRenovation/pages/home_page.rb
- spec/webRenovation/pages/items_page.rb
- spec/webRenovation/pages/pathfinder_page.rb
* Refactors scenarios in the func_webRenovation_spec.rb file to account for design changes to the website
* Edits the page files used in the scenarios mentioned above based on changing page designs
* renamed the accounts_page.rb file to items_page.rb because it describes it better after changes to the website
> Mh wr refactor

- spec/spec_support/inject_sleep.rb
- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/az_databases_page.rb
- spec/webRenovation/pages/az_subjects_page.rb
* Removing sleep injection logic for 'eq' method
* Adding JS error suppression for websites outside WR
* Switching from rspec assertion to capybara assertion within pages/*.rb
> Hp updating sleep injector and fixing minor issues

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/base_page.rb
This scenario tests the functionality of logging in and seeing a visual
change on the page once you are logged in.  The visual change the
scenario is testing for the is when the login button changes to say
My Account after logging in. Alterations were also made on the base page
based on web design changes.
> Adds scenario for logging in and checking homepage

- spec/classes/classes_config.yml
- spec/classes/classes_repo_config.yml
- spec/classes/classes_spec_helper.rb
- spec/classes/integration/int_classes_spec.rb
* spec/classes/ folder holds the config, repo_config, and spec_helper file
* in the spec/classes/integration folder lies the integration test for the
classes API
> Creates QA folder for classes API

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/base_page.rb
- spec/webRenovation/pages/pathfinder_page.rb
Creates a new scenario for the subject pathfinder pages to test every single page listed on the Browse A-Z Subjects page.  
Updates base_page.rb to fix a bug regarding leaving the About tab open 
Updates the pathfinder_page.rb file to fix logic in the on_page? method and changes the 
all(...., range: 1..3) format to all(...., minimum: 1) in methods as pages can have more than three fields.
> Mh pathfinder

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/library_page_navigation.rb
- spec/webRenovation/pages/thesis_and_dissertation_camps.rb
Created a scenario and a new page to locate the Thesis camp page for
Basic Page Scenario 11.
> Added Navigation to the Thesis Camp Page

- spec/webRenovation/pages/home_page.rb
- spec/webRenovation/pages/library_jobs_page.rb
- spec/webRenovation/pages/reseach_guides_page.rb
These changes accomodate the latest site design.
> Hp fixing tests

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/home_page.rb
Small changes to some scenarios regarding new syntax and sleep statements
> Mh refactor wr

- spec/hathitrust/functional/func_hathitrust_spec.rb
- spec/hathitrust/hathitrust_config.yml
- spec/hathitrust/hathitrust_spec_helper.rb
Creates the hathitrust folder along with the hathitrust config and
spec_helper files.
Cretes log in scenario for hathitrust site and tests for log in status
> Creates functional test for HathiTrust login

- spec/oldlibrarysite/functional/func_oldlibrarysite_spec.rb
- spec/oldlibrarysite/oldlibrarysite_config.yml
- spec/oldlibrarysite/oldlibrarysite_spec_helper.rb
Creates the functional test file for logging in
Creates the config and spec_helper files for the test
Creates the necessary folders under the spec folder
> Creates functional test for logging into the old library website

- spec/remix/functional/func_remix_spec.rb
- spec/remix/remix_config.yml
- spec/remix/remix_spec_helper.rb
Creates the file for the functional login test for remix ND.
Creates the config and spec_helper for the test.
Creates the necessary folders
> Creates functional test for login to Remix ND

- spec/honeycomb/functional/func_honeycomb_spec.rb
- spec/honeycomb/honeycomb_config.yml
- spec/honeycomb/honeycomb_spec_helper.rb
Adds a functional test file to the honeycomb folder which tests login
functionality.
Creates config and spec_helper files for honeycomb
> Creates the functional lest for honeycomb login

- spec/webRenovation/pages/courses_page.rb
- spec/webRenovation/webRenovation_config.yml
webRenovation_config.yml now points to beta
fix issue with url syntax in the courses page with File.join
> Update config file to use beta and added File.join to courses page

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/base_page.rb
- spec/webRenovation/pages/pathfinder_page.rb
Adjustments of scope and test scenarios based on the latest code and content changes.
> Hp webrenovation adjust

- spec/spec_support/cas_login.rb
- spec/spec_support/path_parameterizer.rb
And updating parameter handler to allow for more than one parameterized value.
> Adding documentation

- spec/spec_support/swagger_handler.rb
* Prefer more descriptive method names (setting variables instead of
reading variables).
* Remove unused `&block` parameter; that block was not used (instead
it was something passed to `operations.each`)
* Updating memoization of @swagger variable. There was a dispersed
knowledge of what was setting the @swagger variable
> Tweaking swagger handler

- spec/curate/functional/func_curate_spec.rb
- spec/hathitrust/functional/func_hathitrust_spec.rb
- spec/honeycomb/functional/func_honeycomb_spec.rb
- spec/oldlibrarysite/functional/func_oldlibrarysite_spec.rb
- spec/remix/functional/func_remix_spec.rb
- spec/webRenovation/functional/func_webRenovation_spec.rb
* Suppressing js errors from the spec for old library website
* Adding rspec tags for scenarios I want to run on the weekend.
> CAS upgrade testing

- spec/webRenovation/pages/items_page.rb
- spec/webRenovation/pages/technology_lending.rb
These scenarios has minor content changes made to them and have now been
updated to account for them.
> Refactor items page scenario and technology lending scenario

- spec/webRenovation/functional/func_webRenovation_spec.rb
- spec/webRenovation/pages/home_page.rb
- spec/webRenovation/pages/items_page.rb
Small id changes and text changes
> minor changes to scenarios and pages based on content changes

- spec/spec_support/test_runtime.rb
Sometimes testers are providing invalid values for 'ENVIRONMENT'
variable. This change:
* Captures the error and provides guidance to tester
* Exits the spec without running any scenarios
> Handling KeyError for invalid ENVIRONMENT variable

- spec/usurper/functional/func_usurper_spec.rb
- spec/usurper/pages/base_page.rb
- spec/usurper/pages/home_page.rb
- spec/usurper/pages/search_page.rb
> Updating usurper specs to match content and release changes

- spec/spec_support/json_output_formatter.rb
Similar to the check for LoadError, I'm also picking up
SyntaxError.
Related to PR: https://github.com/ndlib/QA_tests/pull/213
> Capturing Syntax error in spec

- README.md
- spec/spec_helper.rb
- spec/spec_support/test_runtime.rb
* Updates documentation to use Chrome headless 
* Provides a toggle to switch drivers
* Configuration for setting up selenium driver with chrome headless
> Support for using chrome headless with Selenium driver

- spec/usurper/pages/base_page.rb
- spec/usurper/pages/home_page.rb
* Documentation
* Removing duplicate assertions
* decoupling tests from content changes
> Hp usurper updates

- spec/contentful/contentful_config.yml
- spec/contentful/contentful_spec_helper.rb
- spec/contentful/integration/int_contentful_spec.rb
- spec/contentful/pages/test_page_preview.rb
- spec/spec_support/contentful_handler.rb
- spec/spec_support/test_runtime.rb
* Adds assertions for page content
* Requires release numbers as an input variable to the spec
* Verifies webhooks are created in contentful space
> Updating tests against contentful

- Gemfile.lock
> use newest version of bunyan_capybara

- .github/ISSUE_TEMPLATE.md
This pull request assists issue creators in providing the details for reporting issues.
More details about this github feature are [here](https://github.com/blog/2111-issue-and-pull-request-templates)
> Making an issue template similar to Hyrax repo

- spec/usurper/pages/az_databases_page.rb
- spec/usurper/pages/az_subjects_page.rb
- spec/usurper/pages/courses_page.rb
- spec/usurper/pages/home_page.rb
- spec/usurper/pages/items_page.rb
* Changes headers from h2 --> h1
* Use 'smart' option on find method for item requests page
> Changes to specs for library website release r20171122

- spec/curate/pages/orcid_home_page.rb
5edf68d6a172091b62d488ee598ccdd49c36f95f
> Updating assertions for ORCID home page

- spec/usurper/pages/search_page.rb
Updates the assertions of onesearch URLs after searching from Usurper homepage.
> Updating onesearch URLs

- spec/spec_support/test_runtime.rb
51073653aabab1a3d70242b26244ebc01adc522c
While writing specs for bendo batch ingestor, I realized we should not
put server names in a public git repo like this one. So the best option
was to store those URLs in corpfs and read from there.
In this pull request:
* Adding a `find_app_host_url` method that checks if the URL in the
spec's config file is a valid URL
* If not, the method checks for the same key in corpfs using the
dictionary built by `PathParameterizer::ParameterFinder` class
* If it doesn't find a URL in these files, the spec aborts
> Changes for reading secret URLs from corpfs

- spec/spec_support/test_runtime.rb
> Fixing syntax for Bunyan logging statement

- spec/microfilms/functional/func_microfilms_spec.rb
- spec/microfilms/microfilms_config.yml
- spec/microfilms/microfilms_spec_helper.rb
- spec/microfilms/pages/home_page.rb
bf7b7bed04541d728a03a5d2a32adf587cb2b95a
* Adds staging URL
* Changes pre-production key to 'prep' for framework consistency
0a14e2a602b809316be4bec2e96f864b2a291f56
5d45b83a655794875a34e6403ff930ccfae808e2
ba06e13aacd2d2c42161a74fe71a6c240ed7e6b7
* Updates scenario names to be more specific
* Moves home page validates to spec/microfilms/pages for framwerk consitency
* Keeps rubocop happy
> Updating medieval microfilms specs

- config/deploy.rb
- config/deploy/production.rb
- spec/curateBatchIngestor/curateBatchIngestor_config.yml
- spec/curateBatchIngestor/curateBatchIngestor_spec_helper.rb
- spec/curateBatchIngestor/functional/func_curateBatchIngestor_spec.rb
- spec/curateBatchIngestor/pages/health_status_page.rb
- spec/curateBatchIngestor/pages/jobs_status_page.rb
368fec02d9653abb96f708faf316b09d5b203894
* Loads the health status page
* Looks up the version number from master branch of curatend-batch repo
* Verifies if the health status page has same version number
* This commit also updates deploy config to support trigger from Jenkins
4e1348bdc48f2ac268d39809652bbcad0edcc3b3
* Adds scenario to load /jobs page
* Verifies that the request returns 200 OK
* Verifies that the response is a non-zero array
* Verifies that each array element has valid hash keys,
'Name' & 'Status', otherwise returns false and fails the scenario
> Scenario to check version of Curate Batch Ingestor

- spec/xur/functional/func_xur_spec.rb
- spec/xur/pages/home_page.rb
- spec/xur/xur_config.yml
- spec/xur/xur_spec_helper.rb
* Loads the homepage and verifies that 2 login buttons exist
> Smoke test for XUR

- spec/seaside/functional/func_seaside_spec.rb
- spec/seaside/pages/base_page.rb
- spec/seaside/pages/home_page.rb
- spec/seaside/seaside_config.yml
- spec/seaside/seaside_spec_helper.rb
* Creates the seaside folder structure
* Creates the BasePage and HomePage classes for the seaside website
* Completes first 'User Browsing' scenario-->'Load Homepage'
> Mh seaside spec

- spec/inquisition/functional/func_inquisition_spec.rb
- spec/inquisition/inquisition_config.yml
- spec/inquisition/inquisition_spec_helper.rb
- spec/inquisition/pages/home_page.rb
- spec/usurper/functional/func_usurper_spec.rb
Commit 1
* Creates folder structure
* Creates pprd and prod urls for .config file
* Sets up inquisition_spec_helper.rb
Commit 2
* Creates the scenario for loading the homepage with smoke_test tag
* Creates the HomePage class to ensure the homepage loads with header, footer, and page content
* Updates spec_helper to require page files
* Updates func_inquisition_spec to use correct spec_helper call
> Mh inquisition

- spec/curate/functional/func_curate_spec.rb
- Changed the expected link text for the collection card associated with this change.
> Fix expectation for DLTP-1262

- spec/usurper/pages/base_page.rb
* Search toggle has been removed from banner
> Usurper website release r20180216

- spec/spec_support/cas_login.rb
* Fixes DLTP-1216
* Enforces all CAS logins to enter passcode on the new login screen
> Enforces passcode for CAS login

- spec/curate/functional/func_curate_spec.rb
- spec/curate/pages/image_page.rb
https://jira.library.nd.edu/projects/DLTP/issues/DLTP-1190?filter=myopenissues
* Creates the createImage method for the ImagePage class
* Adds scenarios dealing with the embargo access rights of Curate works
**Read Commit Definitions for Further Info**
> JIRA DLTP-1097: Curate Embargo Visibility Problems

- spec/hesburghsite/functional/func_hesburghsite_spec.rb
- spec/hesburghsite/hesburghsite_config.yml
1ec18e9d79733606e0c14fc7c33e88e9c4109862
a3848484a8428bc62e6fddc333f6481e14033659
489d9d082a9c28383662dea6eed14e04ade0ee40
> Fr Hesburgh Portal specs

- linter/template/custom_cop_template.rb
This template will serve as a guide to creating future custom rubocops.
> Custom rubocop template for future reference

- spec/microfilms/functional/func_microfilms_spec.rb
- spec/microfilms/microfilms_config.yml
- spec/microfilms/pages/home_page.rb
Removes status code assertion, not supported by Selenium
Removes js error suppression, not supported by Selenium
Updates config URL for microfilms prod
> Cutover of microfilms specs from poltergeist to Selenium

- spec/inquisition/functional/func_inquisition_spec.rb
- spec/inquisition/pages/error_page.rb
- spec/inquisition/pages/home_page.rb
6eeaaf22c060669cfe68e9c20e4b8e0b5ba3c4dc
0c899eb706adda4a855159d1b1631de6dda78208
> Inquisitions spec cutover from poltergeist to Selenium

- spec/curate/functional/func_curate_spec.rb
'Delete' button has been removed from CurateND
@see https://github.com/ndlib/curate_nd/commit/2a82e131be3548f442a7477829ad6c5746a83d70
> Curate v2018.25 spec changes

- README.md
- bin/run_tests
* Adds more clarity to toggles in `bin/run_tests`
* Updates readme for curate pprd specific test example
> Updates docs for more specifics to run tests against curate pprd

- spec/usurper/selenium/usurper_selenium.py
This is the first in, likely, a long series of updates as we rework the website QA stack.
I will be following up with documentation on how to run and possibly scripting around that as well.
> selenium script for homepage tests

- spec/aleph/newman/Aleph.postman_collection.json
- spec/aleph/newman/README.md
Creating an initial suite of some basic API and OPAC checks, along with instructions to follow.
This should close out ESU-973 and future enhancements can be done in other tickets.
> initial QA specs and instructions for Aleph

- spec/usurper/selenium/firefox/spec/usurper_selenium_firefox_search.py
Adds front-end testing of the search function of the Library website in the Firefox browser
> add search tests

- .github/workflows/build-docker-image.yml
This will reject a potential PR if there are any Critical or High level CVE vulnerabilities within the built container. We would ask that these be remediated before the code is accepted, even if the code changes do not impact the Docker build.
> Add docker testing to ci

- Dockerfile
- spec/kiosk/newman/Kiosk.postman_collection.json
Adds smoke test for Kiosk and repairs the vulnerabilities in the Docker build
> Esu 1278 add smoke test

- .github/workflows/build-docker-image.yml
- Dockerfile
Also make the container a bit more lightweight through some best practices for installing updates
Closes ESU-1678
> chore: update ruby container to path vulns

- spec/usurper/puppeteer/chrome/README.md
- spec/usurper/puppeteer/chrome/spec/login.test.js
- spec/usurper/puppeteer/chrome/spec/navigation.test.js
- spec/usurper/puppeteer/chrome/spec/search-events.test.js
Adding tests for the Events pages and the search functionality.
Closes ESU-1687
>  feat: add events search testing

- spec/usurper/puppeteer/chrome/README.md
- spec/usurper/puppeteer/chrome/spec/drop-downs.test.js
End-to-end tests that verify that proper behavior of the dropdown menu links.
Closes ESU-1681
> feat: add dropdown menu testing
