spec/spec_support/verify_network.rb

The following warning was in the STDOUT. It may have been getting lost
in the chatter of the other logged messages.
```console
WARNING: ignoring the provided expectation message argument ([]) since
it is not a string or a proc.
```

Removing network error expectation warning

---

README.md

`git branch master` does not checkout the branch. We should also ensure
that we are deploying using an up to date code version; This is only
relevant if there are upstream changes to the deploy process. We need
to keep those in sync.
Capistrano runs the deploy script locally. It SSH-es into the app
server and pulls the changes from the remote repository (e.g. Github).

Updating README to refine details

---

spec/curate/curate_spec_helper.rb
spec/curate/functional/func_curate_spec.rb

Instead of the explicit require, assume we will use all of the pages
throughout the spec. This removes some mental overhead.

Pushing curate page requirements to helper

---

spec/honeycomb/integration/int_honeycomb_spec.rb

These are not necessary as they are required as part of the Gemfile
declarations.

Removing explicit require

---

spec/spec_support/example_logging.rb

Prior to this change, if there were no keywords, the logged line would
have a trailing tab. This change fixes that.

Removing trailing tabs (\t)

---

.gitignore
spec/curate/functional/func_curate_spec.rb
spec/spec_support/example_logging.rb

With this change, we begin logging the general chatter of the specs
along with the failures of those specs to the same log file.
At present, I am opting to write to both STDOUT and log files; This
way we can see how the specs look when they are run.
DLTP-747

Begin logging examples to files

---

spec/spec_helper.rb
spec/spec_support/example_logging.rb
spec/spec_support/test_runtime.rb

Using the before(:suite) block to create a run ID based on datetime. 
After block is WIP

Creating run ID for tracking test results

---

bin/run_tests
spec/spec_support/example_logging.rb
spec/spec_support/example_logging_constants.rb

Prior to this change, when I ran `./bin/run_tests` I got the following
error. By extracting the constants to a separate file we can reference
the constants to assist in the help text of the `./bin/run_tests`
script.
```console
./ruby/gems/2.3.0/gems/capybara-2.12.1/lib/capybara/node/element.rb:24:in `<module:Node>': uninitialized constant Capybara::Node::Base (NameError)
from ./ruby/gems/2.3.0/gems/capybara-2.12.1/lib/capybara/node/element.rb:3:in `<module:Capybara>'
from ./ruby/gems/2.3.0/gems/capybara-2.12.1/lib/capybara/node/element.rb:2:in `<top (required)>'
from ./ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
from ./ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
from …
```

Ensuring bin/run_tests run outside of bundle exec

---

bin/run_tests
spec/spec_support/example_logging.rb

Many times we test against beta sites that are not fully developed
and/or static assets are not setup correctly. This toggle will allow
testers to skip network traffic validations during dev builds.

Toggle to skip verify_network_traffic

---

spec/spec_support/json_output_formatter.rb

Our custom JsonOutputFormatter is throwing a NameError for
ConsoleCodes core formatter module:
NameError: uninitialized constant RSpec::Core::Formatters::ConsoleCodes
This modules provides helpers for formatting console output

Fix for NameError: uninitialized constant

---

config/deploy.rb
config/deploy/production.rb

Jenkins job has an input parameter list for user to pick app name
to run tests against.
This variable is used by Capistrano as a server roles in
config/deploy/production.rb to determine which server the git repo
needs to be deployed to.
The same variable is used to set rspec command path in
run_test task

Jenkins job support for webRenovation project

---

README.md

macOS has known issues with smb protocol. Switching to cifs
provides more reliability and better performance.
Recommended by ESU team.

Changing protocol for shared drive setup

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/account_details_page.rb
spec/curate/pages/loggedin_page.rb
spec/curate/pages/login_page.rb

This work originated from [failing scenarios](https://jira.library.nd.edu/browse/DLTP-939) against curate prod. I wrote some additional scenarios to fulfill the test coverage gap after addressing test failures. 
In this PR:
* Add scenarios for both type of users: with and without account details updated
* Identify user accounts based on flag in TestCredentials.csv
* Change in random user selection from TestCredentials.csv
* Address failure due to 'My delegates' button not visible for accounts without an updated profile in curate
* Handle scenarios for users without account details updated by validating against 'Account registration page'

Test accounts behavior based on profile setup

---

Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb
spec/spec_support/example_logging.rb

We've found out that the poltergeist driver works well for ReactJS
applications as well.
I'm taking this out of the testing framework to simplify
workstation setup time for other developers. QT5 setup is very cumbersome for MacOS.

Removing webkit

---

spec/spec_support/json_output_formatter.rb

The 'close' method of parent class simply spits out the entire JSON
output which is very hard to read. I'm removing 'super' and explicitly
using JSON.pretty_generate instead.

Pretty printing JSON output for better readability

---

spec/curate/functional/func_curate_spec.rb

The change on line 132 makes it so the test expect the page not to have
any visible ajax modals instead of expect no ajax modals. Without this,
test fails after the first modal tested is closed because it is still
on the page but not visible.  The change on line 134 is necessary
because the otherwise it tests for the opened ajax modal to be visible
before pprd opens the ajax modal.

Updates scenario "modal facets"

---

Gemfile
spec/gatekeeper/gatekeeper_config.yml
spec/gatekeeper/gatekeeper_repo_config.yml
spec/gatekeeper/gatekeeper_spec_helper.rb
spec/gatekeeper/integration/int_gatekeeper_spec.rb
spec/spec_support/request_builder.rb
spec/spec_support/response_validator.rb

Creates the gatekeeper file under the spec folder. 
Updates Gemfile to use swagger-parser instead of swagger-core because swagger core has issues with identifying the security type for API.
Creates the repo_config, config, and spec_helper files for gatekeeper.
Creates a new class RequestBuilder under the spec_support folder use for sending requests to APIs
that have or do not have security.
Creates int_gatekeeper_spec.rb API test.

Mh gatekeeper

---

spec/curate/functional/func_curate_spec.rb
spec/spec_helper.rb
spec/spec_support/sleep_injector.rb

Creates a the SleepInjector module which adds a 2 second sleep statement to the end of Capybara click_on method.  This will aid in removing sleep statements from test code as the statements are often necessary after using click_on to ensure the action has occurred.  Also, this module is included into the spec_helper so it can be used by all tests.  The func_curate_spec.rb was used to test this module and sleep statements have been removed from it.

Mh refactor sleep

---

spec/spec_helper.rb
spec/spec_support/sleep_injector.rb

Changes the sleep_injector.rb file to remove the module format as a class format is simpler. Also, gets rid of overriding the click_on  method since it calls .click so by overriding the .click method, the sleep statement is passed to the click_on method.  Uses method wrapping to override the .click and .trigger methods to add sleep statements.

Mh sleep refactor

---

spec/spec_helper.rb
spec/spec_support/example_logging.rb
spec/spec_support/example_variable_extractor.rb
spec/spec_support/test_runtime.rb

In AWS code build/deploy, new environment URLs are not static and are built on-the-fly. Currently, our QA framework restricts testing against only those endpoints that are listed in spec/appName/appName_config.yml. This pull request allows us to pass a URL as target environment for testing an application/endpoint which will simplify continuous integration of QA testing with AWS.
In this PR I am also refactoring some previous code to simplify module behavior and intent. 
* Refactoring test_runtime.rb to separate modules
* Creates a new module InitializeExample to set Capybara.app_host based on value of ENVIRONMENT

Hp input url

---

spec/spec_support/request_builder.rb

As we do not want to send a request for the "options" verb,
send_security_vs_none now has an outer if statement so that a
pubic_send will only be used for operation verbs other than "options"

Updates RequestBuilder to avoid "options" UI verb

---

spec/spec_helper.rb
spec/spec_support/example_logging.rb
spec/spec_support/test_runtime.rb

This PR is an attempt to reorganize the code into separate modules. 
* improves code documentation
* improve understanding of the flow
* keeps modules focussed on what they're intended for
This pre-work will make it easier to extend the logging framework in ExampleLogging module to integration tests. This PR could use some more refactor:
* How do I call the info/debug/error methods in test_runtime.rb instead of explicitly calling them like:
```ruby
error(context: "FAILED example")
ExampleLogging.current_logger.error(context: "FAILED example")
```

Refactoring code

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/login_page.rb
spec/spec_support/cas_login.rb
spec/spec_support/inject_sleep.rb

Creates a global cas_login.rb page for tests to use in logged in scenarios. As many tests have a login page in the folder, creating a global login page allows for consistency across different tests and reduces amount of code needed.  This page also keeps track of if the a value was passed by the test for account_details_updated to use only the proper test credentials. The functional test for curate has ben updated to utilize this global login page and the curate/pages/login_page.rb has been updateed to only add the checkLoginPage method for the LoginPage class for the curate folder. Inject_sleep.rb has also been updated to include the has_no_selector? method because a sleep statement is sometimes necessary when testing if the completeLogin method logs in and loads the logged in homepage.

Mh login page

---

spec/spec_support/inject_sleep.rb
spec/spec_support/swagger_handler.rb
spec/spec_support/test_runtime.rb

Updates test_runtime.rb to skip verify_network_traffic for integration tests as it is unnecessary for them. Also adds needed 'end' statements to inject_sleep.rb to make it functional.  Lastly, fixes the call to ExampleVariableExtractor in swagger_handler.rb since config: is necessary when calling that class.

Mh verify network

---

spec/crawler/crawl/web_crawler_spec.rb

These changes are adding some robustness to the site crawler based on requirements from ESU team. 
* Additional logging: being able to see which URLs are being hit.
* Showing a prompt to create a local input file
* Catching timeout to unreachable links and continue with rest of spec
I realize this isn't the best implementation based on our current ecosystem. This test works for now and we can refactor at a later point.

Changes to crawler based on ESU requirements

---

spec/crawler/crawl/web_crawler_spec.rb

Linux server doesn't like upper case letters in require statements.
It needs to match the filename.

Changing require statement to lower case

---

README.md

I've enabled remote build triggers on Jenkins job. 
This documentation shows the steps to trigger a QA test remotely.

Documentation for triggering tests remotely

---

spec/gatekeeper/integration/int_gatekeeper_spec.rb
spec/hours/integration/int_hours_spec.rb
spec/spec_support/request_builder.rb

RequestBuilder is now split into different methods to clarify the code.
In addition, a method_case method was added to create a case-when series
based on the operation.verb request (e.g. get, post). This method has an
optional argument *body as certain operation.verbs (such as post, put
) need a body to added in the public_send request.  RequestBuilder
also now has a logger as an instance variable so the status of the
request can be logged.  The hours and gatekeeper int. tests have been
updated to use the new RequestBuilder.

Splits request builder into different methods

---

bin/write_contentful_slugs_to_csv.rb

Uses the api space_id and cdn_token to get a list of the slugs and places
it in a temporary csv file in order to be transferred into the
Google drive.

Creates the Contentful query for url slugs

---

Gemfile
Gemfile.lock
spec/spec_support/contentful_handler.rb
spec/usurper/integration/int_usurper_spec.rb
spec/usurper/usurper_config.yml
spec/usurper/usurper_repo_config.yml
spec/usurper/usurper_spec_helper.rb

Integration test for the usurper content api.  Creates, previews, then deletes an entry in contentful in  order to test the api. Uses https://alpha.library.nd.edu as its prod config because it visits the website with the name of the entry as a slug to make sure the entry is previewed.

Hp usurper tests

---

spec/spec_support/contentful_handler.rb
spec/usurper/integration/int_usurper_spec.rb

Prior to this commit, if an exception was raised during the test, it
could've left a test page in Contentful. This provides another layer of
insurance that we are cleaning up Contentful.

Adding ensure block to clean-up Contentful

---

spec/spec_helper.rb
spec/spec_support/responsive_helper.rb

This module provides methods to set the window size for devices in
landscape and portrait modes.
By default, I'm setting the window size to 1280x800 in landscape
which simulates desktop mode.

ResponsiveHelpers module for changing window size

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/show_article.rb

If the first article found does not have a file, don't treat this as
an error. Instead add a conditional.

Adding conditional for article spec

---

config/deploy.rb

Jenkins was unable to deploy the repo out to testcontroller01.
Kept complaining:
```console
Capfile locked at 3.7.1, but 3.8.2 is loaded
```

Updating capfile lock to 3.8.2

---

spec/recommendationEngine/integration/int_recommendationEngine_spec.rb
spec/recommendationEngine/recommendationEngine_config.yml
spec/recommendationEngine/recommendationEngine_repo_config.yml
spec/recommendationEngine/recommendationEngine_spec_helper.rb
spec/spec_support/path_parameterizer.rb
spec/spec_support/request_builder.rb
spec/spec_support/response_validator.rb

* Creates a test suite for the recommendation engine API
* Adds an if condition to skip checking for security token if schema is missing in the swagger definition
* Adds logic for returning a mock response for 'options' method
This test will fail becuase the get 'libraryinfo' endpoint for recommednation engine is query parameterized. I'm working on another pull request to accomodate that.

Hp recommend engine

---

spec/spec_support/inject_sleep.rb
spec/webRenovation/pages/az_databases_page.rb
spec/webRenovation/pages/base_page.rb
spec/webRenovation/pages/courses_page.rb
spec/webRenovation/pages/header_tab_all_checks.rb
spec/webRenovation/pages/hours_page.rb
spec/webRenovation/pages/items_page.rb
spec/webRenovation/pages/library_giving_page.rb
spec/webRenovation/pages/library_jobs_page.rb
spec/webRenovation/pages/reseach_guides_page.rb
spec/webRenovation/pages/reserve_a_room_page.rb
spec/webRenovation/pages/reserve_a_room_page_services_tab.rb
spec/webRenovation/pages/technology_lending.rb
spec/webRenovation/pages/thesis_and_dissertation_camps.rb

1. Updates pages to use has_selector? because the injected sleep helps wait for the page to load.
2. Fixes URL comparisons in pages to use File.join to ensure proper format of URL
3. Adds or statement to the status_code_ok? method as the status code comes back 304 sometimes due to cloud front caching.
4. Since Library Giving is not on the alpha site, it should not inherit BasePage and should not call super in its instantiation.

Mh refactor

---

spec/spec_support/contentful_handler.rb
spec/usurper/integration/int_usurper_spec.rb

This is a major refactor as it moves responsibilities to other classes,
tidies up logic (not relying on specific error message text), and
moves more logic into initialization to prevent state mutation during
a test.
Disassociating the Handler and the Entry to prevent nosy neighbor
objects over-working each other.

Refactoring Contentful Handler for preview options

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/show_article.rb

These changes make the test suite more robust, avoiding ambiguous match errors.

Hp curate fixes

---

spec/sipity/functional/etd_spec.rb
spec/sipity/pages/submitted_etd.rb
spec/spec_support/cas_login.rb

Instead of using the local login page, the sipity scenarios now use the
global login page.
The submitted_etd.rb file was altered to account for a missing step
in testing the page by clicking the login button.
The cas_login global page now has terms_of_service_accepted as a
instance variable so that accounts which have accepted the terms and
the ones which have no are all tested.

Updates sipity functional test to use global LoginPage

---

spec/classes/classes_config.yml
spec/gatekeeper/gatekeeper_config.yml
spec/hours/hours_config.yml
spec/recommendationEngine/recommendationEngine_config.yml
spec/spec_support/response_validator.rb
spec/usurper/usurper_config.yml

As some APIs have other $refs in the definition of another $ref, the
ResponseValidator now checks for those deeper levels of $refs to get keys for
all of the definitions so that the API result is fully tested against
all of the expected keys. The test does the same thing for the results to make
sure all of the keys are accounted for.
The config file also no has the proper location for the API

Alters the response_validator to check for levels of $refs

---

spec/webRenovation/functional/func_webRenovation_spec.rb
spec/webRenovation/pages/pathfinder_page.rb

As content has changed in regard to what sections are on each pathfinder
page, the pathfinder_page.rb file has been altered to allow for
an instance variable that keeps track of whether or not each page follows
the general format of pathfinder pages. If it does not, it searches
for only the key sections (hours, librarians). This will aid us in testing
the few pages that differ from the general pathfinder content format

Updates Subject Pathfinder scenario due to content changes

---

spec/curate/functional/func_curate_spec.rb

Using '.click' sometimes throws this message:
"Firing a click at co-ordinates [190, 780.5] failed. Poltergeist
detected another element with CSS selector
It may be overlapping the element you are trying to interact with.
If you don't care about overlapping elements,
try using node.trigger('click')."
Based on the error message I'm switching to using ".trigger('click')"

Changing from using '.click' to .trigger('click')

---

spec/spec_support/example_logging_constants.rb
spec/webRenovation/pages/base_page.rb
spec/webRenovation/webRenovation_config.yml

* Setting the correct URLs in config file to allow using 'test' and
'prod' variables from Jenkins job
* Removing assertion for contentful.com as disallowed traffic in
network traffic validation since they are not being remediated in
the near term.
* Adjusts for release 20170802

Updating URL config and allowing contentful img

---

spec/webRenovation/webRenovation_spec_helper.rb

I'm updating the spec config to support TLSv1.2. Without this config
phantomjs returns an error even when the site supports tlsv[0,1,2].
```console
Request to 'https://theta.library.nd.edu/' failed to reach server,
check DNS and/or server status
```

Updating helper to support tlsv1.2

---

spec/usurperContent/integration/int_usurperContent_spec.rb
spec/usurperContent/usurperContent_config.yml
spec/usurperContent/usurperContent_repo_config.yml
spec/usurperContent/usurperContent_spec_helper.rb

NOTE: This spec will fail because SwaggerHandler is not equipped to handle the format of swagger currently being [used](https://github.com/ndlib/usurper_content/blob/master/definitions/swagger.yml)
I will be following up this PR by another one with enhancements to the SwaggerHandler

Spec for usurper_content API

---

spec/spec_support/response_validator.rb

ResponseValidator still searches for ref keys in deeper levels of the
definition but now it accounts for refs that make up the elements
of another key with type array. IF this occurs, the tests now uses that
items property to get the ref and obtain the keys for that ref. This will
help in testing the result body to make sure it has all of the keys.

Updates the response validator for api testing

---

spec/spec_support/swagger_handler.rb

We're trying to use the same swagger definition for all 'DevOps' activities. ([Here's](https://github.com/ndlib/usurper_content/blob/master/definitions/swagger.yml) a sample)
This enhancement makes the SwaggerHandler run a deep search into a yaml file generated by AWS. 
After I finished up this commit, I came across a [DeepFetch method](https://github.com/intridea/hashie#deepfetch) from Hashie gem which could perhaps do something similar. Any thoughts if I should pursue this as a better solution?

Enhancement for SwaggerHandler to read AWS generated swagger defs 

---

spec/spec_support/json_output_formatter.rb

This change handles file loading errors in cases of running tests
against deleted/misspelt spec file locations.
Otherwise the spec proceeds to run injecting runID in @output_hash
variable which isn't initialized yet, and gives a NameError
```console
NameError: uninitialized constant JsonOutputFormatter::RunIdentifier
```

Handling LoadError

---

spec/spec_support/json_output_formatter.rb

@output_hash doesn't hold the :messages key when we run a test that
passes. This results in a KeyError exception:
```console
KeyError Exception: key not found: :messages
```
I'm using a default value of empty array with the Hash#fetch to handle this error.

Handling KeyError with @output_hash

---

spec/spec_support/test_runtime.rb
spec/usurper/pages/base_page.rb
spec/usurper/usurper_config.yml
spec/usurper/usurper_spec_helper.rb

* Updated usurper config
* Adds an assertion for release number in BasePage class of usurper
* Adds a method in InitializeExample module to require VERSION_NUMBER as an ENV variable

Mandating assertion for version number in usurper tests

---

spec/spec_support/cas_login.rb

**This is a temporary fix**
For some reason, when logging into CAS, the trigger('click') on the login
button of the final step is not firing.  This commit alters this final step
by using a do-until loop that clicks the login button until the CAS login
button (and therefore the page) is no longer visible. Thus, this also utilizes the maleficent
sleep injector to wait in between each click as that may be part of the issue. In doing so, it ensures that the login button will be clicked and keep this bug from causing tests to fail.

Updates cas_login.rb to (semi)fix login bug

---

spec/usurper/functional/func_usurper_spec.rb

This is a quick fix to make ensure the homepage loads before next iteration begins.

Adding sleep statement to allow homepage load

---

Gemfile.lock
spec/spec_helper.rb

The Bunyan module now has an path: parameter for its instantiate_all_loggers
method. This parameter is used in the spec_helper to give the location of the
spec folder to the module so it can properly create/update the bunyan_logs folder
and the *.log files. the spec_path variable is used to hold the path structure
to the said spec folder.

The version of bunyan capybara used to use the path parameter

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/orcid_home_page.rb
spec/curate/pages/orcid_settings_page.rb

This scenario logs in with a test user account whose account details have not been updated and checks if the user can get to the ORCID sign up page. 
I'm not testing further scenarios due to following restrictions:
* The ORCID sign up page has a reCAPTCHA that's making it very hard to register as a bot
* Once an account's ORCID id has been created I cannot recreate another one for it. I have only 5 test accounts that can login into CAS, which will get exhausted in few iterations of testing.

Adding new scenario for 'ORCID settings'

---

spec/spec_support/swagger_handler.rb

After we extracted the logger and variable extractor into
a separate gem (https://github.com/ndlib/bunyan_capybara), we did
not refactor the older references to ExampleVariableExtractor.
This causes the swagger handler to fail:
```error
uninitialized constant SwaggerHandler::ExampleVariableExtractor
```
This commit corrects the reference to BunyanVariableExtractor

Fixing reference to ExampleVariableExtractor

---

Gemfile.lock

bunyan_capybara has been updated to solve https://github.com/ndlib/bunyan_capybara/issues/4 using Harsh's guidelines for the RegExp method post_match as seen in the issue.

new gemfile.lock for new version of bunyan_capybara

---

spec/usurper/functional/func_usurper_spec.rb
spec/usurper/pages/base_page.rb
spec/usurper/pages/courses_page.rb
spec/usurper/pages/home_page.rb
spec/usurper/pages/hours_page.rb
spec/usurper/pages/items_page.rb
spec/usurper/pages/library_jobs_page.rb
spec/usurper/pages/reserve_a_room_page_services_tab.rb
spec/usurper/pages/search_page.rb
spec/usurper/pages/technology_lending.rb
spec/usurper/pages/thesis_and_dissertation_camps.rb
spec/usurper/usurper_config.yml

* avoids ambiguous matches by specifying element types and using 'within' blocks
* Adds beta site as a 'prep' URL to the config
* Updates onesearch URLs to the current values
* Changes absolute URLs to regexps
* Accommodates assertions for '#' in URLs

Adjusting tests for library website release  r20171103

---

spec/contentful/contentful_spec_helper.rb
spec/spec_support/contentful_handler.rb
spec/spec_support/test_runtime.rb

* USE_CONTENTFUL_SPACE toggle allows user to specify whether to use prod or prep space
* in test_runtime, adds require_contentful_space method to be referenced in contentful_spec_helper
* require_contentful_space method checks if user used USE_CONTENTFUL_SPACE toggle and if the user provided correct values for it
* Changes read_contentful_tokens method in contentful_handler to use the user specified contentful space to get qa_key

Updates contentful handler to use the new USE_CONTENTFUL_SPACE toggle

---

bin/run_tests

I was attempting to run the tests locally, and encountered errors in
in the command `./bin/run_tests -h`. Below is the error message:
```console
`require': cannot load such file -- ./QA_tests/spec/spec_support/example_logging_constants (LoadError)
```
I believe this is the result of refactoring to using the Bunyan gem. The
change fixes the error and now `./bin/run_tests -h` outputs the help
message.

Updating to allow ./bin/run_tests to work

---

spec/contentful/integration/int_contentful_spec.rb

Previously, the value for lib_cal_id, which represents the contentful parameter,
was hardcoded to a set value.  Now, the scenario gets the value for lib_cal_id
from the test_data/QA/parameters/contentful.yml file hen randomly picks the lib_cal_id
from the available options.  This adds flexibility for the values and helps avoid future code changes
if the values from the yml file change.

Changes lib_cal_id from hard code to dynamic

---

spec/curate/curate_spec_helper.rb
spec/curate/pages/audio_page.rb
spec/spec_support/test_runtime.rb

5127e24d536a0466634c93c87691a9222dd9e370
* Adds an array called 'EXCLUDE_URI_FROM_NETWORK_TRAFFIC_VALIDATION'
that can be used as a hook to exclude URIs in any spec
* Filters out non-URI resources because they don't have response codes
and their validation needs to be handled differently
* Skips verification of resources that have been included in
EXCLUDE_URI_FROM_NETWORK_TRAFFIC_VALIDATION
* Categorizes all network resources into 4 groups, for ease of
troubleshooting and logging
* Adds documentation about the 'verify_network_traffic' method
190ace602b86d989e9f2e3301d50848a669b392a
df3e6c91c256e8b11c6e68552a95220f26595150
For some reason, the curate_spec_helper won't require all files
in spec/curate/pages unless I first explicitly require
`spec/curate/pages/home_page.rb`
Without this …

Fixes curate tests failing due to failed network resources

---

spec/curate/pages/login_page.rb
spec/spec_support/cas_login.rb

5cf6a2bed94aa159dedb85d01eefff7c3880738f
After the CAS upgrade, the login page no longer asks for a passcode
for the testing IDs.
This is a temporary fix and will be reverted once the accounts have
been setup correctly again.
a65f35d02a3dff8c21c8a7b95987489ec8959c37

Updating login specs after CAS upgrade

---

spec/rbsc/functional/func_rbsc_spec.rb
spec/rbsc/rbsc_config.yml

161b6d083b952f1ba20b4ba3468c53f7ace9eb19
* Making keys consistent with staging, prep, prod format, so its easier to run tests across the framework (let's say against all 'prep' envs)
* Adding 'staging' URL
de885da0851371566e865d01d97c5b5db6574cb5
* Adds a 'smoke_test' tag for running specs during large changes
* Adds more assertions to validate homepage

Updates Rbsc specs for meltdown testing

---

spec/spec_support/test_runtime.rb

fc012ffdfd58a2d7bb3979d92e2c736fd545654e
Not all specs are using the hook for excluding URIs from network
validation. In that case the instance variable
'@exclude_uri_from_network_traffic_validation' does not get created and
is 'nil'. The 'verify_network_traffic' method then fails with error:
```error
"class": "NoMethodError",
"message": "undefined method `include?' for nil:NilClass"
```
This fix adds an additional condition to check if the class variable
is not nil.

Fixes condition when instance variable is nil

---

spec/buzz/buzz_config.yml
spec/buzz/buzz_spec_helper.rb
spec/buzz/functional/func_buzz_spec.rb
spec/buzz/pages/buzz_player.rb
spec/spec_support/url_handler.rb

671e34164a32b251781a273be16a8d51b329f7c3
This module will have helper methods to help with URL parsing needs
across the framework
cc62e4a2f026d4a91e323dffd88b4036ccdfda01
* Verifies that buzz server returns a valid JSON
* The assertions make sure that the values of various keys in
the JSON response are set correctly.
* These assertions make sure that the consuming applications are
able to stream
* NOTE: This isn't an ideal way to ensure that the server works
as expected, but is a good start for smoke tests.

Spec for testing buzz for meltdown vulnerability

---

spec/seaside/functional/func_seaside_spec.rb
spec/seaside/pages/about_page.rb
spec/seaside/pages/base_page.rb
spec/seaside/pages/community_page.rb
spec/seaside/pages/history_page.rb
spec/seaside/pages/home_page.rb
spec/seaside/pages/oral_hist_page.rb
spec/seaside/seaside_spec_helper.rb

* Creates the scenarios and page files for all of the pages from the About Seaside dropdown on the top banner
* Updates the spec_helper to require the base_page.rb file before other page files
* Adds smoke_test tag to the 'Loads Homepage' scenario

Mh seaside

---

spec/primo/functional/func_primo_spec.rb
spec/primo/pages/home_page.rb
spec/primo/pages/search_results_page.rb
spec/primo/primo_config.yml
spec/primo/primo_spec_helper.rb

ce37c287ea24f2d3c149ff4ac755d42a08bff829
* Creates folder structure for spec/primo
* Adds first scenario
* Exclude static assets from network verification that are not
loading in non-prod
75c2f7e7aaf46cdecd74a70778864e6bbad2b508
* These methods are serving as helper methods when switching between
onesearch and NDCatalog in the scenarios.
6adbdf50baf87a4a81073710639cd99f66ee2daa
* Loads homepage, checks if Onesearch tab is selected,
enters a search term, clicks search and verifies results page
* Results page verification only checks is the URL is on
Primo and does not verify the URI. I preferred this approach
because the URI has many parameters that keep changing over time
* Results page also verifies status code and if results table is not
empty
c8cf6cabc29fdbdbc789c5620b8d5eecb95271fe …

Tests for searching Primo

---

Gemfile.lock
spec/curate/functional/func_curate_spec.rb
spec/curate/pages/catalog_page.rb
spec/curate/pages/departments_page.rb

bd7802b9f262541e24082c8892609ae09bf4dc12
- Theses search is now a search for all items, updated specs to check that the all items link goes to a basic search
- "Materials" has been changed to "Items" in most places, updated specs to match
- This does not yet add tests for the featured collection cards
3c323e7d28a9334ed405f621cd026cfedb1139ec
- Added new specs to test featured collection card links
- Found a problem with the way some of the specs were written. When performing a "has_content?" check within a "within" block, it would always return a Capybara::Session which is truthy, so was allowing all specs to pass these checks even when they shouldn't. Per the documentation, performing find chain is similar to the intended behavior, so changed several of the within checks to …

DLTP-1203: Featured Collections

---

spec/usurper/pages/header_tab_all_checks.rb
spec/usurper/pages/reseach_guides_page.rb

6f6998feb8a5b169b511c1805cad06b4430fdaf8
The 'research guides' page http://libguides.library.nd.edu/
is outside the realm of these specs. But there are certain
assets on this website that are not loading:
Status: 404 URL: https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js
Status: 403 URL: http://s3.amazonaws.com/libapps/sites/3767/include/img/jesus.gif
Because of these resources the VerifyNetworkTraffic module reports
a 'ResourceError'.
This change adds these to URIs to be excluded from the network
verification
7ff68d6d011eed07a8d24b19234bbc3da0a4c8e9
Based on changes in Usurper (SPA) code
https://github.com/ndlib/usurper/pull/363

Updating specs per library website release r20180126

---

spec/bendo/bendo_config.yml
spec/bendo/bendo_spec_helper.rb
spec/bendo/functional/func_bendo_spec.rb
spec/bendo/pages/health_status_page.rb

0d2fc8e32e592e6ac2dd1f396ab1e068bddc123e
* Endpoint URLs are stored in corpfs
* Checks if the page loads with a '200 OK' and looks for keyword
'Bendo' on the page.
* NOTE: I'm not verifying the version number of bendo in the assertion
This will be verified once I have a confirmation from devs about
their preferred method to store version number in the git repo

Adds a health check for bendo

---

spec/curate/curate_config.yml
spec/curate/pages/home_page.rb
spec/curateBatchIngestor/pages/health_status_page.rb
spec/dec/dec_config.yml
spec/dec/pages/home_page.rb
spec/hesburghsite/hesburghsite_config.yml
spec/microfilms/microfilms_config.yml
spec/primo/primo_config.yml
spec/seaside/pages/home_page.rb
spec/seaside/seaside_config.yml
spec/sipity/pages/home_page.rb
spec/sipity/sipity_config.yml
spec/spec_support/test_runtime.rb
spec/usurper/usurper_config.yml
spec/vatican/pages/home_page.rb
spec/vatican/vatican_config.yml

With the new version of Capybara (2.17.0), the visit method adds a trailing slash to current_url.
This throws off the url tests in the HomePage classes.
To fix this, I have done the following to tests that were failing for the above reason:
* Make sure config files don't have trailing slashes
* always check for current_url with a '/'

Updating config files and current_url tests on HomePage classes

---

spec/curate/functional/func_curate_spec.rb

Added a spec that tests the specific case of rendering collections in thumbnail view on the catalog page. This currently only covers the specific case uncovered by DLTP-1229. There is another ticket to expand this to other thumbnail views (DLTP-1269)

Add coverage for bug DLTP-1229

---

README.md
spec/spec_helper.rb
spec/spec_support/swagger_handler.rb

* Based on https://github.com/ndlib/QA_tests/issues/279
* The SwaggerHandler method, swagger, has been renamed swagger_from_definitions because definitions/swagger.yml is the location of that swagger file
* Code has not been changed
* Creates the new method swagger_from_gateway which is similar to swagger_from definitions except it gets the swagger definition from deploy/gateway
* Removed initial attempt to build swagger and rescue ArguementError because swagger definition is always nested in gateway files
* Adds require_swagger_location which forces tester to specify where the swagger should be loaded from in an ENV hook
* ex: SWAGGER_LOCATION=gateway
* SwaggerHandler.require_swagger_location is run in spec/spec_helper in the before(:suite) hook because SwaggerHandler is instantiated …

Creates swagger_from_gateway method and creates toggle hook

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/catalog_page.rb

Scenario:
* Tests the functionality of the list and grid views of the pages for each Type of Work
Method:
* Opens the ajax model for Types of Work to get the links for all Types of Work
* Puts the href of each link in a separate array to because links become obsolete
* Cycles through the page for each Type of Work and tests:
* if CatalogPage class is on_page
* if the list view is initially selected
* if the resources are in list form with list view selected
* if grid link becomes active when clicked
* if the resources are in grid form when grid view is selected

Creates 'List vs. Grid View of Types of Work' scenario and test_facets_list_vs_grid method

---

bin/run_tests
spec/curate/functional/func_curate_spec.rb
spec/curate/pages/catalog_page.rb
spec/curate/pages/show_article.rb
spec/spec_helper.rb

01ea4980fd08eb60675e7498901b7b837384eac5
- Added a way to disable maleficent. This is useful when iterating on a test that you know is failing
- Added a method to allow searching for a term with spaces. When this happens, the url of the page uses an encoded version of the search term. Changed on_valid_url? to check for encoded search term in the url
- Added a helper method within Article to test if pagination was rendered for the article and with the correct params
- The existing show article spec was not testing file downloads. This has been silently failing for a few reasons. First, the first article that it selects in the search may or may not have files (currently does not for pprd, for example). Second, the has_files? check was silently failing due to ambiguity if the article had …

Add specs for file browsing/pagination

---

spec/curate/pages/show_article.rb

CSS for different types of content are different:
table.table.table-striped.document.attributes
table.table.table-striped.finding_aid.attributes
table.table.table-striped.dataset.attributes
Any of these types of articles could be picked in the '[Show an Article with many files](https://github.com/ndlib/QA_tests/blob/master/spec/curate/functional/func_curate_spec.rb#L544)' or '[Show an Article](https://github.com/ndlib/QA_tests/blob/master/spec/curate/functional/func_curate_spec.rb#L89)' scenarios.
This change generalizes the `within` scope so that 'valid_page_content?'
method can work for verifying the attributes section of different
types of data.

Curate specs, show article page Generalizes `within` scope for attributes field

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/orcid_home_page.rb

* Additional feature tests ORCID page with test users that have AccountDetailUpdated=true
* The on_page? and valid_page_content? methods in the OrcidHomePage class have been modified to take the value of account_details_updated as a parameter so the valid_page_content? method can account for both user types as they are sent to different ORCID pages
* When account_details_updated = false, the scenario tests for the Sign In page
* When account_details_updated = true, the scenario tests for the Registration page

Creates an additional feature testing ORCID

---

spec/curate/functional/func_curate_spec.rb

dab5cc8d6eeec0a4ef9ae87d77f60f5d45d105fc
* Since `js: true` is already there at the feature level, don't need it again at the scenario level
* Even if we do, the correct syntax would be to have `js: true`  after the rspec tags
df11b68551a0b82166b57dd535e8867bc38b3696
This scenario is dependent on data setup, and we're not going to do test data setup in production. So I'm excluding it from running in production using the [SpecFilterManager](https://github.com/ndlib/QA_tests/blob/master/spec/spec_support/spec_filter_manager.rb#L20)

Hp curate spec filters

---

spec/usurper/pages/lib_calendar_page.rb
spec/usurper/pages/reseach_guides_page.rb

e3d24dbc5f0d43ace9d339b9d9e1c278a3b34620
There is a new redirect that appends a query parameter on the
Libguides page to default 'By Subject' tab
7930da2850586efc6425af994413d2e111e7f5a1

Library website release r20180316 updates

---

.rubocop.yml
linter/rspec_tags/check_tags.rb

* As each scenario must have a :read_only or a :nonprod_only tag to specify whether or not the scenario should be run on prod configuration, this linter creates an offense whenever a scenario does not have one of these tags
* Screenshot of offense below

Creates Rubocop linter for checking the RSpec tags of each scenario in a spec file

---

spec/curate/pages/audio_page.rb
spec/inquisition/functional/func_inquisition_spec.rb
spec/inquisition/inquisition_config.yml
spec/inquisition/pages/error_page.rb
spec/primo/pages/home_page.rb
spec/spec_helper.rb
spec/usurper/pages/reseach_guides_page.rb

a357ea120c3cba24c116b37ed48e2882da30a4cf
- Added an ErrorPage spec helper and added a few known scenarios where the app should render these custom error pages
- Changed spec_helper to clear the VerifyNetworkTraffic.exclude_uri_from_network_traffic_validation on tear down of each test. Adding urls to this list will now need to be done as part of each scenario that cares about it, not just when the modules are loaded. In all cases I found, we're using Page helpers to construct this list, so added it to their initialize methods. Currently this will impact primo, inquisition, curate, and usurper tests.
- This does not cover pages that should load with 200

Add tests for inquisitions error pages

---

spec/curate/functional/func_curate_spec.rb

Sometimes the click method doesn't fire actions in Capybara, but wrapping it around trigger method has been more effective. This change addresses that behavior to make the tests more reliable.

Using trigger has been more reliable

---

spec/contentful/integration/int_contentful_spec.rb
spec/usurper/functional/func_usurper_spec.rb

Hotjar error reported by Poltergeist but works fine on Chrome:
```error
"class": "Capybara::Poltergeist::JavascriptError",
"message": "One or more errors were raised in the Javascript code on the
page. If you don't care about these errors, you can ignore them by
setting js_errors: false in your Poltergeist configuration
(see documentation for details).\n\nTypeError: undefined is not an
object (evaluating 'hj.json.parse')\nTypeError: undefined is not an
object (evaluating 'hj.json.parse')\n    at
https://script.hotjar.com/modules-5656fcbdd6d51afbdc19cd90486f0c7d.js:8 in onload"
```

Suppressess js errors on visit page

---

spec/curate/functional/func_curate_spec.rb

* Due to [change in Curate which creates a Person/Profile for new users without account details updated](https://github.com/ndlib/curate_nd/pull/687/files/68045e8c4b08c54d81c000b2103ff49fe3d72e89#diff-55c5b7aecfb519d0e4880eaf2788eb6e), the My Profile ribbon link for these types of users points to the My Profile page instead of to the Update Account Details page
* Thus, scenarios involving this use case needed to be refactored to account for this change.

Refactors curate login scenarios with account_details_updated: false

---

.rubocop.yml

* As the use of eval in the SOLR spec is uniquely safe due to the SOLR Ruby response format, eval is not a security risk in this spec
* So, the spec will be excluded form the Security/Eval rubocop so that an irrelevant offense is not thrown
* As the eval method is not safe to use for other cases, the cop is not disabled completely and will still scan all other files

Excludes spec/solr/**/* from the Security/Eval cop

---

spec/usurper/functional/func_usurper_spec.rb
spec/usurper/pages/lib_calendar_page.rb
spec/usurper/pages/search_page.rb

2b94bc61f71b4a2432a520ddfd8fc249ce350923
8fd54a3b75aeb160844f2a68c4bdf6e81dc13d78
This issue is being tracked with ExLibris
https://jira.library.nd.edu/browse/NUI-168
22182ab84f90250fb04ab8c99bede52c099617a4
* LW homepage returns JS errors:
```error
Unhandled promise rejection TypeError: undefined is not a constructor
(evaluating 'new(window.RTCPeerConnection||window.mozRTCPeerConnection
||window.webkitRTCPeerConnection)({iceServers:[]})')
at https://alpha.library.nd.edu/static/js/main.8f087ce7.js:17
TypeError: undefined is not an object (evaluating 't.rendered')
at https://alpha.library.nd.edu/static/js/main.8f087ce7.js:22 in wt
```
Supressing them in this release so the test cases can continue running
This issue is being tracked in https://jira.library.nd.edu/browse/LW-466
* Changes …

Library website release r20180608

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/loggedin_page.rb
spec/curate/pages/works_page.rb

d58000eb4ab14d15be6acb5fa0b8d33258df279e
Accomodates DLTP-1411
https://github.com/ndlib/curate_nd/pull/705
d2981260af5bf1dfe92e2d480f02be9c1c8f3897
Radio buttons have been changed to links
https://github.com/ndlib/curate_nd/pull/702
Updates Show an Article with many files
a5a486313eb8cf83e6be64d49314eedc24d3493d

Hp curate v2018.19

---

README.md
bin/run_tests
managing_aws_profiles.md

* Adds and cleans up old commands for running tests from README
* Removes duplication of env variables from README and adds missing ones
in bin/run_tests
* Fixes typos in aws-vault documentation

Updates documentation and bin/run_tests

---

.rubocop.yml
spec/curate/functional/func_curate_spec.rb
spec/curate/pages/edit_work_page.rb
spec/curate/pages/image_page.rb
spec/curate/pages/show_article.rb

```console
ENVIRONMENT=pprd CHROME_HEADLESS=true SKIP_CLOUDWATCH=true RUNNING_ON_LOCAL_DEV=true bin/run_tests spec/curate/functional/func_curate_spec.rb:454
```
5ac296640b1d2ed37603aa511ab06950541e9658
15e727d30469212563fa0d3b4581b75697cbed68
* Adds an argument to handle doi radio button selection
* Adds a block of assertions with a case statement
* 'Publisher' is requireed field that needs to be filled in when
minting new doi.
d7294ecebc10244cbc35bdb72ea58a5f237c6b99
* Adds `new_doi_minted_article?` method which asserts the landing page
when a new article is created
* Adds `has_doi?` method that asserts the page once the server has
finished minting a doi
45635d7d0c289a283edd8536f5ea2d0be746469c
* These are the assertions that will be made when a user clicks
'Edit' on an article …

Adds specs for curate DOI features

---

spec/curate/functional/func_curate_spec.rb

`find_link('Delete').click` gives a 'Cancel/OK' prompt in the UI.
So the items are not getting deleted and adding stale data to the
non-prod servers.

Wraps 'Delete' with an 'accept_prompt'

---

spec/usurper/functional/func_usurper_spec.rb
spec/usurper/pages/base_page.rb
spec/usurper/pages/header_tab_all_checks.rb
spec/usurper/pages/home_page.rb
spec/usurper/pages/lib_calendar_page.rb
spec/usurper/pages/library_giving_page.rb
spec/usurper/pages/library_page_navigation.rb
spec/usurper/pages/reseach_guides_page.rb
spec/usurper/pages/reserve_a_room_page.rb
spec/usurper/pages/search_page.rb

0878777023df151af63158ff33383636d9c8976d
I am leveraging Selenium webdriver with Chrome headless. 'status_code'
method is not supported with Selenium.
2bd2f823b5116d15c396b3975304ef3956408084
This method is not supported by Selenium
```error
undefined method `js_errors=' for #<Selenium::WebDriver::Remote::Driver
```
224d3aed8dc2d143156d4e5a51b998ab945b7134
748de02ae820f0d03dfdfe8b59a4808be5d39e37
`Capybara::Driver::Node#trigger` method is not supported with Selenium
driver. Spec raises an error:
```error
Capybara::NotSupportedByDriverError Exception: Capybara::Driver::Node#trigger
```
da28dafe5efb5e960b85fcde0d60082987c83c53
7c6a97c0583ad8261d1942d0c478f112a947a1a3
`switch_to_window` is not supported by Selenium. The correct way
to do the same thing is `switch_to.window`

Cutting over usurper specs to chrome headless

---

spec/usurper/functional/func_usurper_spec.rb
spec/usurper/pages/search_page.rb

* Generalizes url assertion with a regex
* Removes sleep statements and leverages sleep injection in
`page.has_selector?` from Capybara-maleficent gem
* Changes content assertions to look for Primo NUI

Changing asserts to Primo NUI and simplifying search specs

---

spec/usurper/functional/func_usurper_spec.rb
spec/usurper/pages/search_page.rb

8db218ea628e978e42d5fe6e02e4625be2235d8f
* Accommodates http and https
* Accommodates prod and non-prod
non-prod: https://onesearchpprd.library.nd.edu/
prod: http://onesearch.library.nd.edu/
23b4364bb991abd86ba73e34f7f24ebe15f2d607
Escapes . (period) in hostname, otherwise in Ruby Regexp a . is
treated as any character
6c4fd1702b3f7fd8ffa6f35f2286944a028c3669
* Prefers `has_content?` over sleep statements to leverage built-in
wait logic from capybara-maleficent gem
* Adjusts URL assertion using start with so that the assertion stays
valid even with different search parameters

Usurper spec changes for LW release r20180706

---

README.md
spec/curate/functional/func_curate_spec.rb
spec/spec_support/spec_filter_manager.rb

c744911e0426ac65b6aaf23357fd7ca6d2058e1c
88f74b7df648c6b190273d75911eebabfaff5f52
- Created a feature block for all things DOI
- Moved the new DOI test to this block
- Created a test that ensures the doi link on objects will properly redirect back to the object via the doi handler. Tagged for production only since links in pprd will redirect to prod objects, causing a false positive

Test existing DOI link redirection

---

spec/curate/pages/edit_work_page.rb
spec/curate/pages/show_article.rb

With curate release tag v2018.21, doi links will redirect to
https://handle.test.datacite.org/* in non-prod accounts.

Switches assertions for EZid to datacite migration

---

spec/spec_support/cas_login.rb
spec/usurper/pages/library_giving_page.rb

1778a4f4100e2681ce2ca32007ee96adaabb998e
f2145ddf3a995b523cac95f036be59edcaa82df8

Library website r20180720 changes

---

spec/curate/functional/func_curate_spec.rb

All these scenarios were simply logging in and hitting the various
menu items under 'Manage' and 'Deposit' buttons. This needed that many
logins to the site.
Collapsing them into 2 scenarios simplifies readability and shaves
6 mins off of the total execution time of Curate specs.

Flattens 26 scenarios down to 2

---

spec/sipity/pages/dashboard.rb
spec/sipity/pages/etd_submission_page.rb
spec/sipity/pages/etd_welcome.rb
spec/sipity/pages/home_page.rb
spec/sipity/pages/new_deposit.rb
spec/sipity/pages/signed_in_page.rb
spec/sipity/pages/submitted_etd.rb
spec/spec_support/cas_login.rb

`status_code` method is not supported with selenium web driver. These changes remove status code assertions from the sipity pages and the shared LoginPage class

Cuts over sipity specs to use chrome headless

---

spec/sipity/functional/func_sipity_spec.rb
spec/sipity/pages/dashboard.rb
spec/sipity/pages/etd_submission_page.rb
spec/sipity/pages/etd_welcome.rb
spec/sipity/pages/home_page.rb
spec/sipity/pages/new_deposit.rb
spec/sipity/pages/signed_in_page.rb
spec/sipity/pages/submitted_etd.rb

6502dc6f88de53873884775fa5867a3a1bacc0ce
Using File.join helps avoid issues with missing/extra pathname
separators
118057411d830c96ccb579cbcf1bba726247e794
valid_page_content? method uses assertions that have built in
support for wait using Capybara::Maleficient gem.
This provides more breathing room for page to load and makes
specs non-fragile
f0eb5b4208b1e51b00206714ba7781a2a3a1faec
fba2d0166f09ff7256a4555be317d719a1fc1a9a
* Removes circulatory method calls for `visit_home` and `sign_in`
from other methods. Instead calling them from scenarios to improve
readability of scenario
* Adds a method for `sign_out`
* Simplifies feature and scenarios for 'first time' and 'Returning'
users.
* collapses scenarios for 'Returning users' to reduce the number
of logins, improves speed of overall …

Refactors sipity specs

---

spec/curate/functional/func_curate_spec.rb

* Using hash iterations to iterate through each of the featured
collections on the curate home page.
* Having separate scenarios for the same behavior adds execution time in
starting and ending each scenario.
* This takes total execution of 'Featured Collections' feature from
30 sec to 16 secs

Collapses 'Featured Collections' scenarios

---

bin/run_tests
spec/spec_support/aws_ssm_handler.rb

In scenarios when a dev is testing against local machine, and does
not need to access any values from the parameter store, this toggle
will allow the developer to skip setting SSM clients.

Adds a switch to skip setting ssm clients

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/account_page.rb
spec/curate/pages/edit_work_page.rb
spec/curate/pages/faq_page.rb
spec/curate/pages/image_page.rb
spec/curate/pages/loggedin_page.rb
spec/curate/pages/orcid_home_page.rb
spec/curate/pages/show_article.rb

d6e653ba9aea72a4441efa1ef508046e1d581596
This change is based on the curate changes in https://github.com/ndlib/curate_nd/pull/725/commits/3c7adf251b6f076bd52a90c7bead4b29de46d12c
24ee90a173050c2eaa3a8ad12c5bfa227381df75
based on the curate changes in https://github.com/ndlib/curate_nd/pull/727/commits/efc59b1c2f85c161497cf9ba75082f79f5c364b7
d9dccddcc7a78fec1db5106d5c9812152aa96fdd
'Add a Section to my Profile' link has been removed in https://github.com/ndlib/curate_nd/pull/725/commits/5b338fa79ac3fd97bfe047a5caba780c4f01680f
df4bfbd30a123b7ea9685c4e3f5ad237ae346d33
This commit conflates the 2 separate scenarios for accounts with and
without details updated. Reasoning:
Previously on clicking 'ORCID logo Create or Connect your ORCID iD',
accounts that were not updated in CurateND would …

Curate spec changes for DOI release and other changes going along with it

---

spec/curate/pages/home_page.rb

Sometimes the pprd environment loads slowly and in that case I
need to give the 'valid_page_content?' some breathing room for the
page load to finish. Otherwise I'd see this error:
```console
Unable to find visible css \".homepage-search\
```
Moving this assertion outside the 'within' block
leverages Capybara::Maleficent built in wait logic.
This change reduces the brittleness of the  specs in slow environments

Moves 'has_field?' asertion outside 'within' block

---

spec/curate/functional/func_curate_spec.rb
spec/curate/pages/orcid_home_page.rb

a27ae25515d56ef4e38cb37685b6e349981fa7fd
Only ND created DOI links are expected to redirect back to curateND.
Example: https://curate.nd.edu/show/qf85n87433t
Clicking DOI links created by other publishers will direct the browser
to the publishers content.
Example: https://curate.nd.edu/show/kd17cr59n26
541ea57d8d04439b71d63b108a729a0da99e1561
Depending on how the testing accounts are setup across different
environments, the orcid redirect page can either be a sign in or registration
page. This keeps changing as we're testing different environments
and introduces unnecessary flux.
With this change I'm loosening up assertions to a point where it
verifies that the redirect was successful to either of the Orcid page.

Curate fixes for failing specs

---

Gemfile.lock
README.md
bin/run_tests
docker/README.md
spec/spec_support/aws_ssm_handler.rb
spec/spec_support/test_runtime.rb

17cb588b63a00d3568efce7fa5003b7a1d50e9fc
* Removes default behavior of testing with poltergeist and phantomjs
* Adds toggles to switch between local grid and selenium grid. This
is essential because SauceLabs cannot access non-public websites at
the moment.
* Removes method for initializing firefox drivers against local grid.
The intent being to just use one chrome instance to develop test specs
and then use sauce labs infrastructure for all other browsers.
* Adds ability to send sauce lab platform config from environment
variables
aec5e077fbba16db9fa64b62fca203fcae4158e5
2cd7dbaccf8e82bbbb7d8d99990c3870844cfd13
`:region`  and `:credentials` are optional arguments when creating an ssm
client. So when this code is running on ECS, I am depending
on the sdk to figure out the credentials via …

Adds support for running specs using sauce labs infrastructure 

---

spec/usurper/selenium/chrome/run_specs.sh
spec/usurper/selenium/chrome/spec/usurper_selenium_chrome_homepage.py
spec/usurper/selenium/chrome/spec/usurper_selenium_chrome_search.py

Creating a second test script to include search checks. The method used to find the dropdown and select a new search choice is not elegant and could be fragile, so we will want to keep an eye on failure rates - however it appears to be an issue with `chromedriver`. I will be working on creating a set of Firefox/geckodriver checks - this might solve the dropdown issue and allow us to remove the more fragile tests from `spec/usurper/selenium/chrome/spec/usurper_selenium_chrome_search.py`.
I've also added the `implcitly_wait(10)` to the python scripts to allow the pages to wait for elements but continue on as soon as they are found.
I've also updated the `run_specs.sh` script to exit 1 if any of the scripts fail, without continuing on to any subsequent scripts. This should speed up execution …

ESU-1046 Test Search Components

---

.github/workflows/rubocop-ci.yml

Closes #357 by leveraging GitHub Actions for CI

feat(CI): move rubocop check to GitHub Actions

---

README.md
spec/solr/smoke/Solr.postman_collection.json

Checks to see if the Solr server is up and that its web interface has started. Does not check if cores are properly loaded - that would be a functional test for the future

add solr smoke test

---

.gitignore
spec/usurper/puppeteer/Dockerfile
spec/usurper/puppeteer/README.md
spec/usurper/puppeteer/package-lock.json
spec/usurper/puppeteer/package.json
spec/usurper/puppeteer/spec/jest-puppeteer.config.js
spec/usurper/puppeteer/spec/jest.config.js
spec/usurper/puppeteer/spec/login.test.js
spec/usurper/selenium/chrome/Dockerfile
spec/usurper/selenium/chrome/README.md
spec/usurper/selenium/chrome/spec/usurper_selenium_chrome_homepage.py

Due to the nature of the way SPAs are rendered in the browser, selenium doesn't work very well as a testing framework. This adds tests written in Puppeteer, which is a Node library and allows promises to be used as we wait for content to be rendered in the browser, making the front end tests more reliable. 
The tests are also written in a jest style format, making them as approachable as unit tests for some. 
Here, we add two basic tests for expected content - that the browser is going to the right place and that a login button that works is present - along with an end-to-end login check, if appropriate ENV is leveraged. Instructions are in the README for both the Docker build/test and running the test suite without Docker.
Closes ESU-1142

feat: add puppeteer testing for e2e login checks

---

spec/usurper/puppeteer/chrome/README.md
spec/vatican/puppeteer/chrome/README.md
spec/vatican/puppeteer/chrome/package-lock.json
spec/vatican/puppeteer/chrome/package.json
spec/vatican/puppeteer/chrome/spec/e2e.test.js
spec/vatican/puppeteer/chrome/spec/jest-puppeteer.config.js
spec/vatican/puppeteer/chrome/spec/jest.config.js

These tests as written merely replicate the tests that were written in Ruby/rspec previously. Once approved, the Ruby specs could be retired.
Closes ESU-993

feat: migrate convocate tests to puppeteer for chrome
